### ISSUE TITLE
Weighted regression

### ISSUE THREAD

**Issue by davidaknowles** [osorensen/hdme#25]
How hard would it be hard to be able to weight data points differently, i.e. different known noise variance for each observation? 

Thanks!

**Comment by davidaknowles** [comment]
I think for `corrected_lasso_gaussian` at least I can just do 
`Q <- t(W) %*% diag(weights) %*% W - sigmaUU`
`b <-  t(W) %*% diag(weights) %*%  y`
right? (where `sum(weights)=1`).

**Comment by osorensen** [comment]
Dear @davidaknowles, thanks for this very interesting question! Sorry for my very late reply. Apparently I had turned off notifications from this repository, so did not see this issue.

I will think about it, and get back to you as soon as I can.

**Comment by osorensen** [comment]
Hello, and sorry again for being so late. 

I think what you do makes perfect sense when some data points have a higher reliability than others.

This seems like an interesting and useful feature, and I imagine there must be some references to this in the statistical literature? I will add weight option to a future update of the package - perhaps I will be able to do this already in April.

**Comment by osorensen** [comment]
This could be an interesting improvement, e.g., for data with correlated residuals, but it requires more methodological development. Closing for now.
